const terms = [
    // part of speech
    ['Noun', 'Sustantivo', false],
    ['Suru verb', 'Verbo Suru', false],
    ['Ichidan verb', 'Verbo Ichidan', false],
    ['Auxiliary verb', 'Verbo auxiliar', false],
    ['Godan verb with ru ending', 'Verbo godan con terminación ru', false],
    ['Godan verb with mu ending', 'Verbo godan con terminación mu', false],
    ['Godan verb with su ending', 'Verbo godan con terminación su', false],
    ['Godan verb with ku ending', 'Verbo godan con terminación ku', false],
    ['Godan verb with bu ending', 'Verbo godan con terminación bu', false],
    ['Godan verb with u ending', 'Verbo godan con terminación en u', false],
    ['Godan verb - Iku/Yuku special class', 'Verbo Godan - Clase especial Iku/Yuku', false],
    ['Intransitive verb', 'Verbo intransitivo', false],
    ['Noun or verb acting prenominally', 'Sustantivo o verbo que actúa prenominalmente', false],
    ['Noun - used as a prefix', 'Sustantivo: se utiliza como prefijo', false],
    ['Counter', 'Contador', false],
    ['Expression', 'Expresión', false],
    ['Prefix', 'Prefijo', false],
    ['Suffix', 'Sufijo', false],
    ['Wikipedia definition', 'Definición de Wikipedia', false],
    ['Other forms', 'Otras formas', false],
    ['Place', 'Lugar', false],
    ['Notes', 'Notas', false],
    ['Particle', 'Partícula', false],
    [`Adverb taking the 'to' particle`,`Adverbio que toma la partícula 'to'`, false],
    ['Adverbial noun', 'Sustantivo adverbial', false],
    ['Temporal noun', 'Sustantivo temporal', false],
    ['No-adjective', 'Adjetivo No', false],
    ['Na-adjective', 'Adjetivo Na', false],
    ['Adverb', 'Adverbio', false],
    ['I-adjective', 'Adjetivo I', false],
    ['Auxiliary adjective', 'Adjetivo auxiliar', false],
    ['I-adjective (yoi/ii class)', 'Adjetivo I (clase yoi/ii)', false],
    ['Ku-adjective (archaic)', 'Adjetivo Ku (arcaico)', false],
    ['Shiku adjective (archaic)', 'Adjetivo Shiku (arcaico)', false],
    ['Archaic/formal form of na-adjective', 'Forma arcaica/formal de adjetivo Na', false],
    ['Taru-adjective', 'Adjetivo Taru', false],
    ['Pre-noun adjectival', 'Sustantivo pre-adjetival', false],
    ['Pronoun', 'Pronombre', false],
    ['Conjunction', 'Conjunción', false],
    ['Transitive verb', 'Verbo transitivo', false],
    ['Ichidan verb (kureru special class)', 'Verbo Ichidan (clase especial kureru)', false],
    ['Noun - used as a suffix', 'Sustantivo: se utiliza como sufijo', false],
    ['General expression', 'Expresión general', false],

    // notes, info
    ['Usually written using kana alone', 'Generalmente escrito usando sólo kana', false],
    ['Usually written using kanji alone', 'Generalmente escrito usando sólo kanji', false],
    ['Honorific or respectful (sonkeigo)', 'Honorífico o respetuoso (sonkeigo)', false],
    ['Archaism', 'Arcaísmo', false],
    ['oft. as.', 'Usualmente como: ', true],
    ['usu.', 'Usualmente como: ', true],
    ['Historical term', 'Término histórico', false],
    ['Literary or formal term', 'Término literario o formal', false],
    ['Internet slang', 'Jerga de internet', false],
    ['Christian term', 'Término cristiano', false],
    ['Anatomical term', 'Término anatómico', false],
    ['Jocular, humorous term', 'Término comédico, jocoso', false],
    ['Zoology term', 'Término zoológico', false],
    ['Sumo term', 'Término de sumo', false],
    ['Sports term', 'Término deportivo', false],
    ['Shinto term', 'Término sintoista', false],
    ['Music term', 'Término musical', false],
    ['Abbreviation', 'Abreviación', false],
    ['Baseball term', 'Término de beisbol', false],
    ['Mathematics', 'Término matemático', false],
    ['indicates direction or goal', 'Indica dirección u objetivo', false],
    ['pronounced', 'Pronunciado: ', true],
    ['in modern Japanese', 'en japonés moderno', true],
    ['more emphatic than', 'Más enfático que: ', true],
    ['Idiomatic expression', 'Expresión idiomática', false],
    ['Architecture term', 'Término arquitectónico', false],
    ['astronomy, etc. term', 'Término astrológico', false],
    ['biology term', 'Término biológico', false],
    ['botany term', 'Término botánico', false],
    ['business term', 'Término empresarial', false],
    ['economics term', 'Término económico', false],
    ['engineering term', 'Término de ingeniería', false],
    ['finance term', 'Término de finanzas', false],
    ['geology, etc. term', 'Término geológico', false],
    ['law, etc. term', 'Término de derechos, leyes, etc.', false],
    ['Slang', 'Jerga', false],
    ['police slang', 'Jerga policial', false],
    ['Obsolete term', 'Término obsoleto', false],
    ['mahjong term', 'Término de mahjong', false],
    ['shogi term', 'Término shogi', false],
    ['vulgar', 'Término vulgar', false],
    ['sensitive', 'Término sensitivo', false],
    ['rare', 'Término extraño', false],
    ['quotation', 'Cita', false],
    ['physics terminology', 'Término físico', false],
    ['proverb', 'Proverbio', false],
    ['polite (teineigo)', 'Término formal (teineigo)', false],
    ['poetical term', 'Término poético', false],
    ['onomatopoeic or mimetic word', 'Palabra onomatopéyica o mimética', false],
    ['old or irregular kana form', 'Forma kana antigua o irregular', false],
    ['out-dated or obsolete kana usage', 'Uso de kana anticuado u obsoleto', false],
    ['obscure term', 'Término oscuro', false],
    ['numeric', 'Término numérico', false],
    ['military', 'Término militar', false],
    ['male slang', 'Jerga masculina', false],
    ['male term', 'Término masculino', false],
    ['manga slang', 'Jerga de manga', false],
    ['linguistics terminology', 'Término lingüístico', false],
    ['humble (kenjougo) language', 'Término humilde (kenjougo)', false],
    ['geometry term', 'Término geométrico', false],
    ['food term', 'Término de comida', false],
    ['female term', 'Término femenino', false],
    ['familiar language', 'Término familiar', false],
    ['familiar', 'Término familiar', false],
    ['derogatory', 'Término derrogatorio', false],
    ['conjunction', 'Conjunción', false],
    ['colloquialism', 'Coloquialismo', false],
    ['chemistry term', 'Término químico', false],
    ['Buddhist term', 'Término budista', false],
    ['rude or X-rated term', 'Término rudo', false],
    ['martial arts term', 'Término de artes marciales', false],
    ['dialect', '(dialecto)', true],
    ['Only applies to', 'Solo aplica a: ', true],
    ['esp.', 'Especialmente: ', true],
    ['Yojijukugo (four character compound)', 'Yojijukugo (compuesto de cuatro caracteres)', false],
    ['in the construction industry', 'en la industria de la contrucción', true],
    ['of person older than speaker', 'De persona mayor que el hablante', false],
    ['Computer terminology', 'Término computacional', false],
    ["used both to apologize and to get someone's attention", 'utilizado tanto para disculparse como para llamar la atención de alguien', false],
    ['often as 〜', 'usualmente como 〜', true],
    ["Children's language", 'Lenguaje infantil', false],
    ['commonly used until the end of the Meiji period', 'comúnmente utilizado hasta el final del período Meiji', false],
    ['used to address a male patron, customer, or person of high status', 'se utiliza para dirigirse a un patrón masculino, cliente o persona de alto estatus', false],
    ['Product', 'Producto', false],
    ['slightly formal or feminine', 'ligeramente formal o femenino', false],
    ['used by elderly', 'utilizado por personas mayores', false],
    ['used toward people of equal or lower status', 'utilizado hacia personas de igual o menor estatus', false],
    ['mainly used by working men', 'principalmente utilizado por trabajadores', false],
    ['Humble (kenjougo)', 'Término humilde (kenjougo)', false],
    ['spoken to avoid confusion with', 'hablado para evitar la confusión con', true],
    ['とと and ちゃん are used by children', 'とと y ちゃん son utilizados por los niños', false],
    ['Medicine, etc. term', 'Término medicinal', false],
    ['of soil', 'del suelo', false],
    
];

exports.terms = terms;
