const terms = [
    ['Noun', 'Sustantivo'],
    ['Suru verb','Verbo Suru'],
    ['Ichidan verb','Verbo Ichidan'],
    ['Auxiliary verb','Verbo auxiliar'],
    ['Godan verb with ru ending','Verbo godan con terminación ru'],
    ['Godan verb with mu ending','Verbo godan con terminación mu'],
    ['Godan verb with su ending','Verbo godan con terminación su'],
    ['Godan verb with ku ending','Verbo godan con terminación ku'],
    ['Godan verb with bu ending','Verbo godan con terminación bu'],
    ['Godan verb with u ending','Verbo godan con terminación en u'],
    ['Godan verb - Iku/Yuku special class','Verbo Godan - Clase especial Iku/Yuku'],
    ['Intransitive verb','Verbo intransitivo'],
    ['Noun or verb acting prenominally','Sustantivo o verbo que actúa prenominalmente'],
    ['Noun - used as a prefix','Sustantivo: se utiliza como prefijo'],
    ['Counter','Contador'],
    ['Expression','Expresión'],
    ['Prefix','Prefijo'],
    ['Suffix','Sufijo'],
    ['Wikipedia definition','Definición de Wikipedia'],
    ['Other forms','Otras formas'],
    ['Place','Lugar'],
    ['Notes','Notas'],
    ['Particle','Partícula'],
    ['Adverbial noun','Sustantivo adverbial'],
    ['Temporal noun','Sustantivo temporal'],
    ['No-adjective','Adjetivo No'],
    ['Na-adjective','Adjetivo Na'],
    ['Adverb','Adverbio'],
    ['I-adjective','Adjetivo I'],
    ['Auxiliary adjective','Adjetivo auxiliar'],
    ['I-adjective (yoi/ii class)','Adjetivo I (clase yoi/ii)'],
    ['Ku-adjective (archaic)','Adjetivo Ku (arcaico)'],
    ['Shiku adjective (archaic)','Adjetivo Shiku (arcaico)'],
    [`Adverb taking the 'to' particle`,`Adverbio que toma la partícula 'to'`],
    ['Archaic/formal form of na-adjective','Forma arcaica/formal de adjetivo Na'],
    ['Taru-adjective','Adjetivo Taru'],
    ['Pre-noun adjectival','Sustantivo pre-adjetival'],
    ['Pronoun','Pronombre'],
    ['Conjunction','Conjunción'],
    ['Transitive verb','Verbo transitivo'],
    ['Ichidan verb (kureru special class)','Verbo Ichidan (clase especial kureru)'],
    ['Noun - used as a suffix','Sustantivo: se utiliza como sufijo'],
    ['General expression','Expresión general']
];

exports.terms = terms;
